export const SITE_CONFIG = {
  name: "ChurchOS",
  description: "Plateforme moderne, sécurisée et unifiée de gestion pour églises, ministères et assemblées chrétiennes.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://churchos.io",
  ogImage: "/og-image.png",
  links: {
    twitter: "https://twitter.com/churchos",
    github: "https://github.com/churchos",
  },
  supportedCurrencies: [
    { code: "USD", symbol: "$", label: "Dollar américain (USD)" },
    { code: "EUR", symbol: "€", label: "Euro (EUR)" },
    { code: "BIF", symbol: "FBu", label: "Franc burundais (BIF)" },
    { code: "CDF", symbol: "FC", label: "Franc congolais (CDF)" },
    { code: "KES", symbol: "KSh", label: "Shilling kényan (KES)" },
    { code: "TZS", symbol: "TSh", label: "Shilling tanzanien (TZS)" },
    { code: "UGX", symbol: "USh", label: "Shilling ougandais (UGX)" },
  ],
  supportedTimezones: [
    { value: "Africa/Bujumbura", label: "Bujumbura (CAT / UTC+2)" },
    { value: "Africa/Kinshasa", label: "Kinshasa (WAT / UTC+1)" },
    { value: "Africa/Lubumbashi", label: "Lubumbashi (CAT / UTC+2)" },
    { value: "Africa/Nairobi", label: "Nairobi (EAT / UTC+3)" },
    { value: "Africa/Dar_es_Salaam", label: "Dar es Salaam (EAT / UTC+3)" },
    { value: "Europe/Paris", label: "Paris (CET / UTC+1)" },
    { value: "America/New_York", label: "New York (EST / UTC-5)" },
  ],
  roles: [
    "SUPER_ADMIN",
    "CHURCH_OWNER",
    "PASTOR",
    "ADMIN",
    "ACCOUNTANT",
    "SECRETARY",
    "MINISTRY_LEADER",
    "GROUP_LEADER",
    "VOLUNTEER",
    "MEMBER",
  ] as const,
  plans: [
    {
      id: "FREE",
      name: "Free",
      description: "Pour démarrer et structurer une communauté naissante.",
      memberLimit: 100,
      priceMonthly: 0,
      features: [
        "Jusqu'à 100 membres",
        "Gestion des cultes & présences",
        "Enregistrement des dons",
        "1 Campus",
      ],
    },
    {
      id: "STARTER",
      name: "Starter",
      description: "Pour les églises locales en pleine croissance.",
      memberLimit: 500,
      priceMonthly: 29,
      features: [
        "Jusqu'à 500 membres",
        "Groupes & Ministères",
        "Comptabilité & Budgets",
        "QR Code Présence",
        "Exports de rapports",
      ],
    },
    {
      id: "PRO",
      name: "Pro",
      description: "Pour les grandes églises et ministères structurés.",
      memberLimit: -1, // Illimité
      priceMonthly: 79,
      features: [
        "Membres illimités",
        "Suivi pastoral sécurisé",
        "Bibliothèque de sermons & médias",
        "Rapports financiers avancés",
        "Support prioritaire",
      ],
    },
    {
      id: "ENTERPRISE",
      name: "Enterprise",
      description: "Pour les réseaux d'églises, dénominations et multi-campus.",
      memberLimit: -1,
      priceMonthly: 199,
      features: [
        "Multi-campus illimité",
        "Rôles personnalisés",
        "API & Webhooks dédiés",
        "Accompagnement personnalisé",
        "SLA 99.9%",
      ],
    },
  ],
};
